# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        menu_files:
            uri_prefix: /images/files
            upload_destination: '%kernel.project_dir%/public/images/files'
            namer: menu_file_namer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
